# Generated by Django 5.2.13 on 2026-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='powerbi_embed_url',
            field=models.URLField(blank=True, help_text="URL d'intégration PowerBI (Embed URL) spécifique à ce rôle", null=True),
        ),
    ]
