# Generated by Django 5.2.13 on 2026-05-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_role_powerbi_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allowed_ml_models',
            field=models.JSONField(blank=True, default=list, help_text="Liste des IDs de modèles ML autorisés pour ce décideur (ex: ['provider_budget_model'])"),
        ),
    ]
