# Generated by Django 5.2.13 on 2026-05-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DWHEventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwh_id', models.CharField(help_text='ID unique depuis le DWH', max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('guests', models.IntegerField(blank=True, null=True)),
                ('date_from_dwh', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
